'use strict';
const KEY='ecocode_v3';
const scenarios=[
{id:'camp',title:'Поход с друзьями',desc:'Собираетесь на стоянку. Нужно решить, как организовать отдых без лишнего риска.',icon:'⛺',meta:'уровень 1 · ≈ 5 мин',questions:[
{tag:'НАБЛЮДЕНИЕ',text:'Вы пришли на место. С чего начать?',answers:[['Сразу разжечь костёр','wrong','Сначала нужно оценить условия и убедиться, что открытый огонь здесь вообще допустим.'],['Проверить правила и условия на сегодня','correct','Верно. Ограничения могут меняться из-за пожароопасной обстановки.'],['Пойти искать самое сухое место','wrong','Сухая растительность — дополнительный риск, а не преимущество.']]},
{tag:'РЮКЗАК',text:'В рюкзаке есть спички. Что важно сделать?',answers:[['Оставить их рядом с местом отдыха','wrong','Открытый огонь не должен становиться случайным источником опасности.'],['Убрать так, чтобы они не стали случайным источником огня','correct','Верно. Главное — не создавать лишний риск.'],['Проверить спички, поджигая одну','wrong','Экспериментировать с огнём на природе нельзя.']]},
{tag:'МЕСТО',text:'Рядом сухая трава, а ветер усиливается. Что выбираешь?',answers:[['Продолжить как обычно','wrong','Условия стали менее безопасными. Риск нужно снижать, а не игнорировать.'],['Отказаться от открытого огня и выбрать безопасный вариант отдыха','correct','Да. Ветер и сухая растительность повышают опасность распространения огня.'],['Поставить костёр ближе к сухой траве, чтобы было теплее','wrong','Это повышает риск распространения огня.']]},
{tag:'СИТУАЦИЯ',text:'Ты заметил опасное возгорание неподалёку. Твой первый шаг?',answers:[['Подойти ближе, чтобы рассмотреть','wrong','Опасное возгорание нельзя превращать в объект для осмотра.'],['Сообщить взрослым и при необходимости позвонить 112','correct','Верно. При обнаружении возгорания МЧС рекомендует сообщать по 101 или 112.'],['Снять видео и подождать','wrong','Сначала безопасность и сообщение о возгорании, а не наблюдение.']]},
{tag:'ФИНАЛ',text:'Перед уходом со стоянки что важнее всего?',answers:[['Проверить только рюкзак','wrong','Нужно убедиться, что после отдыха не осталось источника опасности.'],['Убедиться, что место оставлено безопасным и без источников огня','correct','Да. Безопасность важнее скорости ухода.'],['Оставить всё как есть, если огня не видно','wrong','Нельзя исходить только из того, что огня не видно.']]}
]},
{id:'fish',title:'Рыбалка в тундре',desc:'Ветер меняется, погода портится. Учись замечать риск до того, как он станет проблемой.',icon:'◌',meta:'уровень 2 · ≈ 5 мин',questions:[
{tag:'ПОГОДА',text:'Перед выходом погода выглядит сухой и ветреной. Что учитываешь?',answers:[['Только температуру','wrong','Для пожарной безопасности важны не только ощущения от температуры.'],['Официальные предупреждения и местные ограничения','correct','Верно. Условия и ограничения нужно проверять перед отдыхом.'],['Ничего, ведь дождя сейчас нет','wrong','Отсутствие дождя само по себе не делает ситуацию безопасной.']]},
{tag:'ОТДЫХ',text:'Компания хочет использовать открытый огонь. Что делаешь?',answers:[['Проверяю, разрешён ли он сейчас и здесь','correct','Да. Правила зависят от действующих ограничений и обстановки.'],['Разрешаю, если огонь маленький','wrong','Размер огня не отменяет действующие ограничения.'],['Выбираю место рядом с сухой растительностью','wrong','Сухая растительность увеличивает риск.']]},
{tag:'ВЕТЕР',text:'Ветер заметно усилился. Самое разумное решение?',answers:[['Сделать огонь выше','wrong','Усиление ветра — причина снижать риск.'],['Отказаться от открытого огня','correct','Верно. Это простое решение резко снижает риск.'],['Перенести огонь ближе к палатке','wrong','Так делать опаснее, а не безопаснее.']]},
{tag:'СООБЩЕНИЕ',text:'Увидел дым от природного пожара. Что делать?',answers:[['Подойти и проверить руками, горячо ли','wrong','Приближаться к опасному пожару не нужно.'],['Сообщить взрослым и позвонить 101 или 112','correct','Верно. МЧС ЯНАО прямо напоминает сообщать о возгорании по 101 или 112.'],['Ничего, если дым далеко','wrong','Даже удалённое возгорание важно передать взрослым и службам.']]},
{tag:'ФИНАЛ',text:'Какой принцип забираешь с собой?',answers:[['Сначала скорость','wrong','Безопасность начинается с оценки ситуации.'],['Сначала условия и последствия, потом действие','correct','Именно так работает ответственное поведение на природе.'],['Сначала эксперимент','wrong','Открытый огонь не место для экспериментов.']]}
]},
{id:'picnic',title:'Семейный пикник',desc:'Нужно выбрать безопасный формат отдыха и заметить признаки меняющейся обстановки.',icon:'✦',meta:'уровень 3 · ≈ 5 мин',questions:[
{tag:'ПЛАН',text:'Семья собирается на природу. Что проверяете заранее?',answers:[['Только список еды','wrong','Для безопасного отдыха важны ещё правила и обстановка.'],['Правила места и актуальные ограничения','correct','Верно. Ограничения могут вводиться при высокой пожарной опасности.'],['Только заряд телефона','wrong','Заряд полезен, но не заменяет оценку условий.']]},
{tag:'МЕСТО',text:'Вы нашли сухую траву и думаете о костре. Решение?',answers:[['Не использовать открытый огонь','correct','Да. Сухая растительность — лишний риск.'],['Развести небольшой костёр','wrong','Маленький огонь всё равно может стать источником пожара.'],['Проверить ветер, бросив траву в огонь','wrong','Эксперименты с огнём не нужны.']]},
{tag:'ДЕТИ',text:'Младшие дети играют рядом с местом отдыха. Что меняешь?',answers:[['Оставляю всё как есть','wrong','Нужно организовать пространство безопаснее.'],['Убираю потенциальные источники опасности и держу детей под присмотром взрослых','correct','Верно. Безопасная организация пространства важна не меньше правил.'],['Предлагаю детям самим следить за огнём','wrong','Ответственность за безопасность должна оставаться у взрослых.']]},
{tag:'ДЫМ',text:'Появился дым вдалеке. Что делать?',answers:[['Игнорировать','wrong','Дым может быть признаком природного пожара.'],['Сообщить взрослым и при необходимости в 101/112','correct','Верно. При обнаружении возгорания МЧС рекомендует сообщать по 101 или 112.'],['Идти навстречу дыму','wrong','К источнику опасности приближаться не следует.']]},
{tag:'ФИНАЛ',text:'Как выглядит хороший туристический навык?',answers:[['Уметь быстро разжечь огонь','wrong','Навык ответственного туриста — не создавать лишнего риска.'],['Уметь заметить риск и вовремя выбрать безопасное решение','correct','Да. Именно это тренирует ЭкоКод.'],['Уметь скрыть следы отдыха','wrong','Главное — безопасно организовать отдых и не оставлять источников опасности.']]}
]}
];
const state={name:'',xp:0,done:{},streak:0};
let current=null,qIndex=0,risk=0,sessionXP=0,safe=0,hotspots=new Set(),actionUsed={};
function load(){try{const x=JSON.parse(localStorage.getItem(KEY)||'{}');if(x&&typeof x==='object'){state.name=typeof x.name==='string'?x.name.slice(0,24):'';state.xp=Number.isFinite(x.xp)?Math.max(0,x.xp):0;state.done=x.done&&typeof x.done==='object'?x.done:{};state.streak=Number.isFinite(x.streak)?Math.max(0,x.streak):0;}}catch(e){}}
function save(){try{localStorage.setItem(KEY,JSON.stringify({name:state.name,xp:state.xp,done:state.done,streak:state.streak}));}catch(e){}}
function $(id){return document.getElementById(id)}
function toast(t){const el=$('toast');el.textContent=t;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2600)}
function view(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id==='view-'+id));document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===id));window.scrollTo({top:0,behavior:'smooth'});if(id==='sim')renderScenarios();if(id==='progress')renderProgress()}
function openProfile(){$('nameInput').value=state.name;$('profileModal').classList.add('show');setTimeout(()=>$('nameInput').focus(),30)}
function closeProfile(){$('profileModal').classList.remove('show')}
function saveProfile(){const n=$('nameInput').value.trim().replace(/\s+/g,' ').slice(0,24);state.name=n;save();updateHeader();closeProfile();toast(n?`Рад снова видеть тебя, ${n}!`:'Профиль очищен.')}
function updateHeader(){const n=state.name||'Гость';$('profileName').textContent=n;$('homeGreeting').textContent=n?`С возвращением, ${n}. Имя и игровой прогресс хранятся только в этом браузере.`:'Сохраняем только имя/ник и игровой прогресс на этом устройстве.';$('progressTitle').textContent=n?`${n}, твой прогресс`:'Твой прогресс';$('totalXP').textContent=state.xp+' XP'}
function start(id){current=scenarios.find(s=>s.id===id);if(!current)return;qIndex=0;risk=0;sessionXP=0;safe=0;hotspots=new Set();actionUsed={};$('game').hidden=false;$('game').scrollIntoView({behavior:'smooth',block:'start'});$('gameTitle').textContent=current.title;renderQuestion();updateScene()}
function renderScenarios(){const list=$('scenarioList');list.textContent='';scenarios.forEach((s,i)=>{const unlocked=i===0||state.done[scenarios[i-1].id];const card=document.createElement('article');card.className='scenario-card'+(unlocked?'':' locked');card.setAttribute('role','button');card.tabIndex=unlocked?0:-1;const icon=document.createElement('div');icon.className='sc-icon';icon.textContent=s.icon;const body=document.createElement('div');const t=document.createElement('div');t.className='sc-title';t.textContent=s.title;const d=document.createElement('div');d.className='sc-desc';d.textContent=s.desc;const m=document.createElement('div');m.className='sc-meta';m.textContent=s.meta+' · 5 решений';body.append(t,d,m);const st=document.createElement('span');st.className='status '+(state.done[s.id]?'done':unlocked?'open':'');st.textContent=state.done[s.id]?'✓ пройден':unlocked?'играть':'закрыт';card.append(icon,body,st);if(unlocked){card.addEventListener('click',()=>start(s.id));card.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();start(s.id)}})}list.append(card)});const done=scenarios.filter(s=>state.done[s.id]).length;$('overallProgressText').textContent=`${done} / ${scenarios.length}`;$('overallProgressBar').style.width=(done/scenarios.length*100)+'%'}
function renderQuestion(){const q=current.questions[qIndex];$('gameStep').textContent=`Решение ${qIndex+1} из ${current.questions.length}`;$('questionTag').textContent=q.tag;$('questionCount').textContent=`${qIndex+1} / ${current.questions.length}`;$('questionText').textContent=q.text;const a=$('answers');a.textContent='';q.answers.forEach((x,i)=>{const b=document.createElement('button');b.className='answer';b.type='button';b.textContent=x[0];b.addEventListener('click',()=>answer(b,x[1],x[2]));a.append(b)});$('feedback').className='feedback';$('feedback').textContent='';$('waterBtn').disabled=false;$('adultBtn').disabled=false;$('callBtn').disabled=false;$('questionBox').style.display='block';$('result').classList.remove('show')}
function answer(btn,kind,fb){document.querySelectorAll('.answer').forEach(b=>b.disabled=true);const ok=kind==='correct';btn.classList.add(ok?'correct':'wrong');const f=$('feedback');f.textContent='';const b=document.createElement('b');b.textContent=ok?'Правильный выбор. ':'Разберём выбор. ';f.append(b,document.createTextNode(fb));f.classList.add('show');if(ok){risk=Math.max(0,risk-8);sessionXP+=25;safe++;state.streak++}else{risk=Math.min(100,risk+18);sessionXP+=5;state.streak=0}state.xp+=ok?25:5;save();$('gameXP').textContent=sessionXP;updateScene();setTimeout(()=>{if(qIndex<current.questions.length-1){qIndex++;renderQuestion()}else finish()},900)}
function finish(){state.done[current.id]=true;save();$('questionBox').style.display='none';$('result').classList.add('show');$('resultXP').textContent=sessionXP;$('resultRisk').textContent=risk<25?'низкий':risk<55?'средний':'высокий';$('resultDecisions').textContent=`${safe}/5`;$('resultTitle').textContent=risk<25?'Маршрут под контролем':risk<55?'Ты заметил часть риска':'Риск оказался слишком высоким';$('resultText').textContent=risk<25?'Отлично: ты не просто запомнил правило, а несколько раз выбрал решение, которое снижает риск.':risk<55?'Хорошая попытка. Повтори сценарий и посмотри, где можно было раньше заметить опасность.':'Главный вывод: безопасность начинается ещё до того, как появляется опасная ситуация.';renderScenarios();renderProgress()}
function updateScene(){const s=$('scene');s.classList.toggle('scene-low',risk<25);s.classList.toggle('scene-mid',risk>=25&&risk<55);s.classList.toggle('scene-high',risk>=55);$('riskMeter').style.width=risk+'%';$('riskMeter').style.background=risk<25?'var(--green)':risk<55?'var(--amber)':'var(--red)';$('riskLabel').textContent=risk<25?'низкий':risk<55?'средний':'высокий';$('gameXP').textContent=sessionXP}
function inspect(type){if(hotspots.has(type))return;hotspots.add(type);const messages={bag:'В рюкзаке нет «магического» безопасного огня: лучший инструмент — заранее проверить правила и убрать лишние источники риска.',fire:'Место отдыха выглядит красиво, но сухая растительность и ветер — повод отказаться от открытого огня.',sky:'Условия меняются. Перед отдыхом важно учитывать официальные предупреждения и действующие ограничения.'};toast(messages[type]);const id={bag:'spotBag',fire:'spotFire',sky:'spotSky'}[type];$(id).classList.add('used');sessionXP+=5;$('gameXP').textContent=sessionXP}
function mini(type){if(actionUsed[type])return;actionUsed[type]=true;if(type==='water'){risk=Math.max(0,risk-12);toast('Риск снижен: ты выбрал безопасное действие.')}if(type==='adult'){risk=Math.max(0,risk-8);toast('Хороший шаг: взрослый помогает оценить ситуацию.')}if(type==='call'){risk=0;toast('Если обнаружено опасное возгорание — сообщают по 101 или 112. Не приближайся к огню.')}$(type==='water'?'waterBtn':type==='adult'?'adultBtn':'callBtn').disabled=true;updateScene()}
function replay(){if(current)start(current.id)}
function back(){$('game').hidden=true;$('questionBox').style.display='';$('result').classList.remove('show');view('sim')}
function renderProgress(){const done=scenarios.filter(s=>state.done[s.id]).length;$('totalXP').textContent=state.xp+' XP';$('doneCount').textContent=`${done} / ${scenarios.length}`;$('safeStreak').textContent=state.streak;const badges=[['🌱','Первый шаг','Пройден 1 сценарий',done>=1],['🧭','Осторожный маршрут','Пройдено 2 сценария',done>=2],['✦','ЭкоКод','Пройдены все сценарии',done>=3],['🔥','Без лишнего риска','Последняя игра с низким риском',state.streak>=5]];const wrap=$('badges');wrap.textContent='';badges.forEach(b=>{const x=document.createElement('article');x.className='badge'+(b[3]?'':' locked');const medal=document.createElement('div');medal.className='medal';medal.textContent=b[0];const title=document.createElement('strong');title.textContent=b[1];const desc=document.createElement('span');desc.textContent=b[2];x.append(medal,title,desc);wrap.append(x)})}
function reset(){if(!confirm('Сбросить имя и игровой прогресс на этом устройстве?'))return;try{localStorage.removeItem(KEY)}catch(e){}location.reload()}
function bind(){document.querySelectorAll('[data-view]').forEach(v=>v.addEventListener('click',e=>{e.preventDefault();view(v.dataset.view)}));document.querySelectorAll('[data-action]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();const x=a.dataset.action;if(x==='start'){view('sim');setTimeout(()=>start(scenarios.find(s=>!state.done[s.id])?.id||scenarios[0].id),150)}if(x==='how'){document.querySelector('.section').scrollIntoView({behavior:'smooth'})}if(x==='profile')openProfile();if(x==='reset')reset()}));$('profileBtn').addEventListener('click',openProfile);$('closeModal').addEventListener('click',closeProfile);$('saveName').addEventListener('click',saveProfile);$('nameInput').addEventListener('keydown',e=>{if(e.key==='Enter')saveProfile()});$('profileModal').addEventListener('click',e=>{if(e.target===$('profileModal'))closeProfile()});$('spotBag').addEventListener('click',()=>inspect('bag'));$('spotFire').addEventListener('click',()=>inspect('fire'));$('spotSky').addEventListener('click',()=>inspect('sky'));$('waterBtn').addEventListener('click',()=>mini('water'));$('adultBtn').addEventListener('click',()=>mini('adult'));$('callBtn').addEventListener('click',()=>mini('call'));$('replayBtn').addEventListener('click',()=>{replay()});$('backBtn').addEventListener('click',back);$('resetBtn').addEventListener('click',reset)}
load();updateHeader();bind();renderScenarios();renderProgress();
if(!state.name)setTimeout(openProfile,500);
